version: 0.2

phases:
  install:
    commands:
      - curl -fsSL https://rpm.nodesource.com/setup_24.x | bash -
      - yum install -y nodejs
      - node -v
      - npm -v
  build:
    commands:
      - npm ci || npm install

artifacts:
  files:
    - '**/*'